title: "Mapping Violence in Early Modern Italy, 1450-1750"
languageCode: "en-us"
baseURL: "https://earlymodernviolence.org"

params:
  tagline: "Insert clever tagline here"
  description: "Insert description here."

markup:
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - taxonomy
  - taxonomyTerm

permalinks:
  news: /:year/:month/:day/:slug/

build:
  noJSConfigInAssets: true
